patterns_and_insertions:
    [
        # Use single ticks for regex patterns
        # http://blogs.perl.org/users/tinita/2018/03/strings-in-yaml---to-quote-or-not-to-quote.html
        # You need to escape \ with \\ in the pattern, for instance for \\todo
        # Use Python named groups https://docs.python.org/3/library/re.html#regular-expression-examples
        # Escape {{ and }} in the insertion expression
        # 
        # Optional:
        # Set strip_whitespace to n to disable white space stripping while replacing the pattern. (Default: y)

        {
            "pattern" : '(?:\\figcomp{\s*)(?P<first>.*?)\s*}\s*{\s*(?P<second>.*?)\s*}\s*{\s*(?P<third>.*?)\s*}',
            "insertion" : '\parbox[c]{{ {second} \linewidth}} {{ \includegraphics[width= {third} \linewidth]{{figures/{first} }} }}',
            "description" : "Replace figcomp",
            # "strip_whitespace": n 
        },
        {
            "pattern": '(?s)(?<!\\newif)\\ifshowcameraready\b(?:[ \t]*\r?\n)?(?P<keep>.*?)(?:\r?\n)?[ \t]*\\else\b.*?\\fi\b',
            "insertion": '{keep}',
            "description": "Keep true branch of ifshowcameraready",
            "strip_whitespace": False 
        },
        {
            "pattern": '(?s)(?<!\\newif)\\ifshowextended\b(?:[ \t]*\r?\n)?(?P<keep>.*?)(?:\r?\n)?[ \t]*\\else\b.*?\\fi\b',
            "insertion": '{keep}',
            "description": "Keep true branch of ifshowextended",
            "strip_whitespace": False 
        }
    ]
# These need to be specified in the command line
verbose: True
compress_pdf: True
keep_bib: True

# if_exceptions: ['showcameraready', 'ifshowextended']
commands_to_delete: [
    'exthide',
    # 'newcommand'
]
commands_only_to_delete: [
    'extshow',
    'prhide',
]

images_allowlist: {
    'images/particle_filter_vid.pdf': 100000
}